### PR TITLE
Create new Base model and db.py

### PR DESCRIPTION
**Pull request by SilverStrings024**
Created a BaseModelMixin to give access to utility functions and have them accessed from any model that subclasses BaseModelMixin.
Also created db.py which contains the database engine and a session object so we don't have too many sessions open at once and our code is much more consolidated.
Please note that I could not push the users/models.py changes due to conflicts.

### CODE REVIEW

**Comment by SilverStrings024** [comment]
If anyone would like to add sqlalchemy specific functions, try to add them to the BaseModelMixin so all models/everyone has access to them. If you have any questions let me know!

**Review by dproc96 — APPROVED** [review]
The code for this looks great and will make our lives a lot easier! One thing before merging, can you move the models into one folder `/server/models` and rename the models.py file that stores the user into user.py?

**Comment by SilverStrings024** [comment]
> The code for this looks great and will make our lives a lot easier! One thing before merging, can you move the models into one folder `/server/models` and rename the models.py file that stores the user into user.py?

Just to be completely clear, you'd like all models (including the BaseModelMixin) to be moved into a model folder with the user model file renamed to user.py right?

**Review by dproc96 — APPROVED** [review]
Looks good to go!

**Pull request merged**
